// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"
	"time"
)

const createAuthToken = `-- name: CreateAuthToken :exec
INSERT INTO auth_tokens (token, email, expires_at)
VALUES (?, ?, ?)
`

type CreateAuthTokenParams struct {
	Token     string
	Email     string
	ExpiresAt time.Time
}

func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) error {
	_, err := q.db.ExecContext(ctx, createAuthToken, arg.Token, arg.Email, arg.ExpiresAt)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token, email, expires_at)
VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	Token     string
	Email     string
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.Token, arg.Email, arg.ExpiresAt)
	return err
}

const deleteExpiredAuthTokens = `-- name: DeleteExpiredAuthTokens :exec
DELETE FROM auth_tokens WHERE expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredAuthTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredAuthTokens)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const getAuthTokenByToken = `-- name: GetAuthTokenByToken :one
SELECT id, token, email, expires_at, used_at, created_at FROM auth_tokens
WHERE token = ? AND used_at IS NULL AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetAuthTokenByToken(ctx context.Context, token string) (AuthToken, error) {
	row := q.db.QueryRowContext(ctx, getAuthTokenByToken, token)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Email,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, token, email, expires_at, created_at FROM sessions
WHERE token = ? AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, token)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Email,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const markAuthTokenUsed = `-- name: MarkAuthTokenUsed :exec
UPDATE auth_tokens SET used_at = CURRENT_TIMESTAMP WHERE token = ?
`

func (q *Queries) MarkAuthTokenUsed(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, markAuthTokenUsed, token)
	return err
}
