// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cited_authors.sql

package db

import (
	"context"
)

const deleteCitedAuthor = `-- name: DeleteCitedAuthor :exec
DELETE FROM cited_authors
WHERE id = ? AND researcher_id = ?
`

type DeleteCitedAuthorParams struct {
	ID           int64
	ResearcherID string
}

func (q *Queries) DeleteCitedAuthor(ctx context.Context, arg DeleteCitedAuthorParams) error {
	_, err := q.db.ExecContext(ctx, deleteCitedAuthor, arg.ID, arg.ResearcherID)
	return err
}

const deleteCitedAuthorsByResearcher = `-- name: DeleteCitedAuthorsByResearcher :exec
DELETE FROM cited_authors WHERE researcher_id = ?
`

func (q *Queries) DeleteCitedAuthorsByResearcher(ctx context.Context, researcherID string) error {
	_, err := q.db.ExecContext(ctx, deleteCitedAuthorsByResearcher, researcherID)
	return err
}

const deleteSyncedCitedAuthor = `-- name: DeleteSyncedCitedAuthor :exec
DELETE FROM cited_authors
WHERE researcher_id = ? AND openalex_id = ? AND source = 'openalex_sync'
`

type DeleteSyncedCitedAuthorParams struct {
	ResearcherID string
	OpenalexID   string
}

func (q *Queries) DeleteSyncedCitedAuthor(ctx context.Context, arg DeleteSyncedCitedAuthorParams) error {
	_, err := q.db.ExecContext(ctx, deleteSyncedCitedAuthor, arg.ResearcherID, arg.OpenalexID)
	return err
}

const insertCitedAuthor = `-- name: InsertCitedAuthor :exec
INSERT INTO cited_authors (researcher_id, openalex_id, name, affiliation, citation_count, source)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertCitedAuthorParams struct {
	ResearcherID  string
	OpenalexID    string
	Name          string
	Affiliation   string
	CitationCount int64
	Source        string
}

func (q *Queries) InsertCitedAuthor(ctx context.Context, arg InsertCitedAuthorParams) error {
	_, err := q.db.ExecContext(ctx, insertCitedAuthor,
		arg.ResearcherID,
		arg.OpenalexID,
		arg.Name,
		arg.Affiliation,
		arg.CitationCount,
		arg.Source,
	)
	return err
}

const isActiveCitedAuthor = `-- name: IsActiveCitedAuthor :one
SELECT COUNT(*) > 0 AS is_cited_author FROM cited_authors
WHERE researcher_id = ? AND openalex_id = ? AND active = 1
`

type IsActiveCitedAuthorParams struct {
	ResearcherID string
	OpenalexID   string
}

func (q *Queries) IsActiveCitedAuthor(ctx context.Context, arg IsActiveCitedAuthorParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isActiveCitedAuthor, arg.ResearcherID, arg.OpenalexID)
	var is_cited_author bool
	err := row.Scan(&is_cited_author)
	return is_cited_author, err
}

const listCitedAuthorsByResearcher = `-- name: ListCitedAuthorsByResearcher :many
SELECT id, researcher_id, openalex_id, name, affiliation, citation_count, created_at, source, active FROM cited_authors
WHERE researcher_id = ?
ORDER BY citation_count DESC
LIMIT 60
`

func (q *Queries) ListCitedAuthorsByResearcher(ctx context.Context, researcherID string) ([]CitedAuthor, error) {
	rows, err := q.db.QueryContext(ctx, listCitedAuthorsByResearcher, researcherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CitedAuthor
	for rows.Next() {
		var i CitedAuthor
		if err := rows.Scan(
			&i.ID,
			&i.ResearcherID,
			&i.OpenalexID,
			&i.Name,
			&i.Affiliation,
			&i.CitationCount,
			&i.CreatedAt,
			&i.Source,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncedCitedAuthorIDs = `-- name: ListSyncedCitedAuthorIDs :many
SELECT openalex_id FROM cited_authors
WHERE researcher_id = ? AND source = 'openalex_sync'
`

func (q *Queries) ListSyncedCitedAuthorIDs(ctx context.Context, researcherID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSyncedCitedAuthorIDs, researcherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var openalex_id string
		if err := rows.Scan(&openalex_id); err != nil {
			return nil, err
		}
		items = append(items, openalex_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopActiveCitedAuthorsByResearcher = `-- name: ListTopActiveCitedAuthorsByResearcher :many
SELECT id, researcher_id, openalex_id, name, affiliation, citation_count, created_at, source, active FROM cited_authors
WHERE researcher_id = ? AND active = 1
ORDER BY citation_count DESC
LIMIT ?
`

type ListTopActiveCitedAuthorsByResearcherParams struct {
	ResearcherID string
	Limit        int64
}

func (q *Queries) ListTopActiveCitedAuthorsByResearcher(ctx context.Context, arg ListTopActiveCitedAuthorsByResearcherParams) ([]CitedAuthor, error) {
	rows, err := q.db.QueryContext(ctx, listTopActiveCitedAuthorsByResearcher, arg.ResearcherID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CitedAuthor
	for rows.Next() {
		var i CitedAuthor
		if err := rows.Scan(
			&i.ID,
			&i.ResearcherID,
			&i.OpenalexID,
			&i.Name,
			&i.Affiliation,
			&i.CitationCount,
			&i.CreatedAt,
			&i.Source,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleCitedAuthorActive = `-- name: ToggleCitedAuthorActive :exec
UPDATE cited_authors SET active = NOT active
WHERE id = ? AND researcher_id = ?
`

type ToggleCitedAuthorActiveParams struct {
	ID           int64
	ResearcherID string
}

func (q *Queries) ToggleCitedAuthorActive(ctx context.Context, arg ToggleCitedAuthorActiveParams) error {
	_, err := q.db.ExecContext(ctx, toggleCitedAuthorActive, arg.ID, arg.ResearcherID)
	return err
}

const upsertSyncedCitedAuthor = `-- name: UpsertSyncedCitedAuthor :exec
INSERT INTO cited_authors (researcher_id, openalex_id, name, affiliation, citation_count, source, active)
VALUES (?, ?, ?, ?, ?, 'openalex_sync', 1)
ON CONFLICT (researcher_id, openalex_id) DO UPDATE SET
    name = excluded.name,
    affiliation = excluded.affiliation,
    citation_count = excluded.citation_count
WHERE cited_authors.source = 'openalex_sync'
`

type UpsertSyncedCitedAuthorParams struct {
	ResearcherID  string
	OpenalexID    string
	Name          string
	Affiliation   string
	CitationCount int64
}

func (q *Queries) UpsertSyncedCitedAuthor(ctx context.Context, arg UpsertSyncedCitedAuthorParams) error {
	_, err := q.db.ExecContext(ctx, upsertSyncedCitedAuthor,
		arg.ResearcherID,
		arg.OpenalexID,
		arg.Name,
		arg.Affiliation,
		arg.CitationCount,
	)
	return err
}
