// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coauthors.sql

package db

import (
	"context"
)

const getCoAuthorByOpenAlexID = `-- name: GetCoAuthorByOpenAlexID :one
SELECT id, researcher_id, openalex_id, name, affiliation, collaboration_count, last_collaborated, created_at FROM co_authors
WHERE researcher_id = ? AND openalex_id = ?
LIMIT 1
`

type GetCoAuthorByOpenAlexIDParams struct {
	ResearcherID int64
	OpenalexID   string
}

func (q *Queries) GetCoAuthorByOpenAlexID(ctx context.Context, arg GetCoAuthorByOpenAlexIDParams) (CoAuthor, error) {
	row := q.db.QueryRowContext(ctx, getCoAuthorByOpenAlexID, arg.ResearcherID, arg.OpenalexID)
	var i CoAuthor
	err := row.Scan(
		&i.ID,
		&i.ResearcherID,
		&i.OpenalexID,
		&i.Name,
		&i.Affiliation,
		&i.CollaborationCount,
		&i.LastCollaborated,
		&i.CreatedAt,
	)
	return i, err
}

const isCoAuthor = `-- name: IsCoAuthor :one
SELECT COUNT(*) > 0 AS is_coauthor FROM co_authors
WHERE researcher_id = ? AND openalex_id = ?
`

type IsCoAuthorParams struct {
	ResearcherID int64
	OpenalexID   string
}

func (q *Queries) IsCoAuthor(ctx context.Context, arg IsCoAuthorParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isCoAuthor, arg.ResearcherID, arg.OpenalexID)
	var is_coauthor bool
	err := row.Scan(&is_coauthor)
	return is_coauthor, err
}

const listCoAuthorsByResearcher = `-- name: ListCoAuthorsByResearcher :many
SELECT id, researcher_id, openalex_id, name, affiliation, collaboration_count, last_collaborated, created_at FROM co_authors
WHERE researcher_id = ?
ORDER BY collaboration_count DESC
`

func (q *Queries) ListCoAuthorsByResearcher(ctx context.Context, researcherID int64) ([]CoAuthor, error) {
	rows, err := q.db.QueryContext(ctx, listCoAuthorsByResearcher, researcherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoAuthor
	for rows.Next() {
		var i CoAuthor
		if err := rows.Scan(
			&i.ID,
			&i.ResearcherID,
			&i.OpenalexID,
			&i.Name,
			&i.Affiliation,
			&i.CollaborationCount,
			&i.LastCollaborated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopCoAuthorsByResearcher = `-- name: ListTopCoAuthorsByResearcher :many
SELECT id, researcher_id, openalex_id, name, affiliation, collaboration_count, last_collaborated, created_at FROM co_authors
WHERE researcher_id = ?
ORDER BY collaboration_count DESC
LIMIT ?
`

type ListTopCoAuthorsByResearcherParams struct {
	ResearcherID int64
	Limit        int64
}

func (q *Queries) ListTopCoAuthorsByResearcher(ctx context.Context, arg ListTopCoAuthorsByResearcherParams) ([]CoAuthor, error) {
	rows, err := q.db.QueryContext(ctx, listTopCoAuthorsByResearcher, arg.ResearcherID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoAuthor
	for rows.Next() {
		var i CoAuthor
		if err := rows.Scan(
			&i.ID,
			&i.ResearcherID,
			&i.OpenalexID,
			&i.Name,
			&i.Affiliation,
			&i.CollaborationCount,
			&i.LastCollaborated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCoAuthor = `-- name: UpsertCoAuthor :exec
INSERT INTO co_authors (researcher_id, openalex_id, name, affiliation, collaboration_count, last_collaborated)
VALUES (?, ?, ?, ?, 1, ?)
ON CONFLICT(researcher_id, openalex_id) DO UPDATE SET
    name = excluded.name,
    affiliation = excluded.affiliation,
    collaboration_count = co_authors.collaboration_count + 1,
    last_collaborated = excluded.last_collaborated
`

type UpsertCoAuthorParams struct {
	ResearcherID     int64
	OpenalexID       string
	Name             string
	Affiliation      string
	LastCollaborated string
}

func (q *Queries) UpsertCoAuthor(ctx context.Context, arg UpsertCoAuthorParams) error {
	_, err := q.db.ExecContext(ctx, upsertCoAuthor,
		arg.ResearcherID,
		arg.OpenalexID,
		arg.Name,
		arg.Affiliation,
		arg.LastCollaborated,
	)
	return err
}
