// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: field_selections.sql

package db

import (
	"context"
)

const deleteFieldSelection = `-- name: DeleteFieldSelection :exec
DELETE FROM researcher_field_selections
WHERE researcher_id = ? AND level = ? AND openalex_id = ?
`

type DeleteFieldSelectionParams struct {
	ResearcherID int64
	Level        string
	OpenalexID   string
}

func (q *Queries) DeleteFieldSelection(ctx context.Context, arg DeleteFieldSelectionParams) error {
	_, err := q.db.ExecContext(ctx, deleteFieldSelection, arg.ResearcherID, arg.Level, arg.OpenalexID)
	return err
}

const listFieldSelectionsByResearcher = `-- name: ListFieldSelectionsByResearcher :many
SELECT id, researcher_id, level, openalex_id, display_name FROM researcher_field_selections
WHERE researcher_id = ?
ORDER BY level, display_name
`

func (q *Queries) ListFieldSelectionsByResearcher(ctx context.Context, researcherID int64) ([]ResearcherFieldSelection, error) {
	rows, err := q.db.QueryContext(ctx, listFieldSelectionsByResearcher, researcherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResearcherFieldSelection
	for rows.Next() {
		var i ResearcherFieldSelection
		if err := rows.Scan(
			&i.ID,
			&i.ResearcherID,
			&i.Level,
			&i.OpenalexID,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFieldSelection = `-- name: UpsertFieldSelection :exec
INSERT INTO researcher_field_selections (researcher_id, level, openalex_id, display_name)
VALUES (?, ?, ?, ?)
ON CONFLICT(researcher_id, level, openalex_id) DO UPDATE SET
    display_name = excluded.display_name
`

type UpsertFieldSelectionParams struct {
	ResearcherID int64
	Level        string
	OpenalexID   string
	DisplayName  string
}

func (q *Queries) UpsertFieldSelection(ctx context.Context, arg UpsertFieldSelectionParams) error {
	_, err := q.db.ExecContext(ctx, upsertFieldSelection,
		arg.ResearcherID,
		arg.Level,
		arg.OpenalexID,
		arg.DisplayName,
	)
	return err
}
