// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type AuthToken struct {
	ID        int64
	Token     string
	Email     string
	ExpiresAt time.Time
	UsedAt    sql.NullTime
	CreatedAt time.Time
}

type CitedAuthor struct {
	ID            int64
	ResearcherID  string
	OpenalexID    string
	Name          string
	Affiliation   string
	CitationCount int64
	CreatedAt     time.Time
	Source        string
	Active        int64
}

type NewsletterItem struct {
	ID                 int64
	NewsletterRunID    int64
	OpenalexID         string
	Title              string
	Authors            string
	PublicationDate    string
	Doi                string
	RelevancyScore     float64
	Summary            string
	IsCitedAuthorPaper int64
	CitedAuthorName    string
	CreatedAt          time.Time
}

type NewsletterRun struct {
	ID             int64
	ResearcherID   string
	Status         string
	PapersFound    int64
	PapersIncluded int64
	HtmlContent    string
	CreatedAt      time.Time
	CompletedAt    sql.NullTime
}

type Publication struct {
	ID              int64
	OpenalexID      string
	ResearcherID    string
	Title           string
	PublicationDate string
	Doi             string
	CitedByCount    int64
	CreatedAt       time.Time
}

type Researcher struct {
	ID                 string
	OpenalexID         string
	Name               string
	Affiliation        string
	HIndex             int64
	WorksCount         int64
	CitedByCount       int64
	RelevancyThreshold float64
	LastSyncedAt       sql.NullTime
	CreatedAt          time.Time
	ResearchInterests  string
	Email              sql.NullString
}

type ScannedWork struct {
	ID              int64
	ResearcherID    string
	ScanMonth       string
	OpenalexID      string
	Title           string
	Doi             sql.NullString
	PublicationDate sql.NullString
	CitedByCount    sql.NullInt64
	Abstract        sql.NullString
	Authorships     string
	Topics          string
	FetchedAt       sql.NullTime
	SourceName      string
	SourceCitedness float64
}

type Session struct {
	ID        int64
	Token     string
	Email     string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Topic struct {
	ID           int64
	ResearcherID string
	OpenalexID   string
	Name         string
	Subfield     string
	Field        string
	Domain       string
	Score        float64
	CreatedAt    time.Time
	Source       string
}
