// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type CitedAuthor struct {
	ID            int64
	ResearcherID  int64
	OpenalexID    string
	Name          string
	Affiliation   string
	CitationCount int64
	CreatedAt     time.Time
	Source        string
	Active        int64
}

type NewsletterItem struct {
	ID                 int64
	NewsletterRunID    int64
	OpenalexID         string
	Title              string
	Authors            string
	PublicationDate    string
	Doi                string
	RelevancyScore     float64
	Summary            string
	IsCitedAuthorPaper int64
	CitedAuthorName    string
	CreatedAt          time.Time
}

type NewsletterRun struct {
	ID             int64
	ResearcherID   int64
	Status         string
	PapersFound    int64
	PapersIncluded int64
	HtmlContent    string
	CreatedAt      time.Time
	CompletedAt    sql.NullTime
}

type OpenalexTopic struct {
	ID           int64
	OpenalexID   string
	DisplayName  string
	Description  string
	Keywords     string
	SubfieldID   string
	SubfieldName string
	FieldID      string
	FieldName    string
	DomainID     string
	DomainName   string
	WorksCount   int64
	UpdatedAt    time.Time
}

type Publication struct {
	ID              int64
	OpenalexID      string
	ResearcherID    int64
	Title           string
	PublicationDate string
	Doi             string
	CitedByCount    int64
	CreatedAt       time.Time
}

type Researcher struct {
	ID                 int64
	OpenalexID         string
	Name               string
	Affiliation        string
	HIndex             int64
	WorksCount         int64
	CitedByCount       int64
	RelevancyThreshold float64
	LastSyncedAt       sql.NullTime
	CreatedAt          time.Time
	ResearchInterests  string
}

type ResearcherFieldSelection struct {
	ID           int64
	ResearcherID int64
	Level        string
	OpenalexID   string
	DisplayName  string
}

type ScannedWork struct {
	ID              int64
	ResearcherID    int64
	ScanWeek        string
	OpenalexID      string
	Title           string
	Doi             sql.NullString
	PublicationDate sql.NullString
	CitedByCount    sql.NullInt64
	Abstract        sql.NullString
	Authorships     string
	Topics          string
	FetchedAt       sql.NullTime
	SourceName      string
	SourceCitedness float64
}

type Topic struct {
	ID           int64
	ResearcherID int64
	OpenalexID   string
	Name         string
	Subfield     string
	Field        string
	Domain       string
	Score        float64
	CreatedAt    time.Time
	Source       string
}
