// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: newsletters.sql

package db

import (
	"context"
)

const createNewsletterItem = `-- name: CreateNewsletterItem :exec
INSERT INTO newsletter_items (newsletter_run_id, openalex_id, title, authors, publication_date, doi, relevancy_score, summary, is_cited_author_paper, cited_author_name)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateNewsletterItemParams struct {
	NewsletterRunID    int64
	OpenalexID         string
	Title              string
	Authors            string
	PublicationDate    string
	Doi                string
	RelevancyScore     float64
	Summary            string
	IsCitedAuthorPaper int64
	CitedAuthorName    string
}

func (q *Queries) CreateNewsletterItem(ctx context.Context, arg CreateNewsletterItemParams) error {
	_, err := q.db.ExecContext(ctx, createNewsletterItem,
		arg.NewsletterRunID,
		arg.OpenalexID,
		arg.Title,
		arg.Authors,
		arg.PublicationDate,
		arg.Doi,
		arg.RelevancyScore,
		arg.Summary,
		arg.IsCitedAuthorPaper,
		arg.CitedAuthorName,
	)
	return err
}

const createNewsletterRun = `-- name: CreateNewsletterRun :one
INSERT INTO newsletter_runs (researcher_id, status)
VALUES (?, 'pending')
RETURNING id, researcher_id, status, papers_found, papers_included, html_content, created_at, completed_at
`

func (q *Queries) CreateNewsletterRun(ctx context.Context, researcherID int64) (NewsletterRun, error) {
	row := q.db.QueryRowContext(ctx, createNewsletterRun, researcherID)
	var i NewsletterRun
	err := row.Scan(
		&i.ID,
		&i.ResearcherID,
		&i.Status,
		&i.PapersFound,
		&i.PapersIncluded,
		&i.HtmlContent,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getNewsletterRun = `-- name: GetNewsletterRun :one
SELECT id, researcher_id, status, papers_found, papers_included, html_content, created_at, completed_at FROM newsletter_runs WHERE id = ? LIMIT 1
`

func (q *Queries) GetNewsletterRun(ctx context.Context, id int64) (NewsletterRun, error) {
	row := q.db.QueryRowContext(ctx, getNewsletterRun, id)
	var i NewsletterRun
	err := row.Scan(
		&i.ID,
		&i.ResearcherID,
		&i.Status,
		&i.PapersFound,
		&i.PapersIncluded,
		&i.HtmlContent,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listNewsletterItems = `-- name: ListNewsletterItems :many
SELECT id, newsletter_run_id, openalex_id, title, authors, publication_date, doi, relevancy_score, summary, is_cited_author_paper, cited_author_name, created_at FROM newsletter_items
WHERE newsletter_run_id = ?
ORDER BY is_cited_author_paper DESC, relevancy_score DESC
`

func (q *Queries) ListNewsletterItems(ctx context.Context, newsletterRunID int64) ([]NewsletterItem, error) {
	rows, err := q.db.QueryContext(ctx, listNewsletterItems, newsletterRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NewsletterItem
	for rows.Next() {
		var i NewsletterItem
		if err := rows.Scan(
			&i.ID,
			&i.NewsletterRunID,
			&i.OpenalexID,
			&i.Title,
			&i.Authors,
			&i.PublicationDate,
			&i.Doi,
			&i.RelevancyScore,
			&i.Summary,
			&i.IsCitedAuthorPaper,
			&i.CitedAuthorName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewsletterRunsByResearcher = `-- name: ListNewsletterRunsByResearcher :many
SELECT id, researcher_id, status, papers_found, papers_included, html_content, created_at, completed_at FROM newsletter_runs
WHERE researcher_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListNewsletterRunsByResearcherParams struct {
	ResearcherID int64
	Limit        int64
}

func (q *Queries) ListNewsletterRunsByResearcher(ctx context.Context, arg ListNewsletterRunsByResearcherParams) ([]NewsletterRun, error) {
	rows, err := q.db.QueryContext(ctx, listNewsletterRunsByResearcher, arg.ResearcherID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NewsletterRun
	for rows.Next() {
		var i NewsletterRun
		if err := rows.Scan(
			&i.ID,
			&i.ResearcherID,
			&i.Status,
			&i.PapersFound,
			&i.PapersIncluded,
			&i.HtmlContent,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNewsletterRun = `-- name: UpdateNewsletterRun :exec
UPDATE newsletter_runs
SET status = ?, papers_found = ?, papers_included = ?, html_content = ?, completed_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateNewsletterRunParams struct {
	Status         string
	PapersFound    int64
	PapersIncluded int64
	HtmlContent    string
	ID             int64
}

func (q *Queries) UpdateNewsletterRun(ctx context.Context, arg UpdateNewsletterRunParams) error {
	_, err := q.db.ExecContext(ctx, updateNewsletterRun,
		arg.Status,
		arg.PapersFound,
		arg.PapersIncluded,
		arg.HtmlContent,
		arg.ID,
	)
	return err
}
