// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: openalex_topics.sql

package db

import (
	"context"
)

const countOpenAlexTopics = `-- name: CountOpenAlexTopics :one
SELECT COUNT(*) FROM openalex_topics
`

func (q *Queries) CountOpenAlexTopics(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenAlexTopics)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOpenAlexTopicByOpenAlexID = `-- name: GetOpenAlexTopicByOpenAlexID :one
SELECT id, openalex_id, display_name, description, keywords, subfield_id, subfield_name, field_id, field_name, domain_id, domain_name, works_count, updated_at FROM openalex_topics WHERE openalex_id = ? LIMIT 1
`

func (q *Queries) GetOpenAlexTopicByOpenAlexID(ctx context.Context, openalexID string) (OpenalexTopic, error) {
	row := q.db.QueryRowContext(ctx, getOpenAlexTopicByOpenAlexID, openalexID)
	var i OpenalexTopic
	err := row.Scan(
		&i.ID,
		&i.OpenalexID,
		&i.DisplayName,
		&i.Description,
		&i.Keywords,
		&i.SubfieldID,
		&i.SubfieldName,
		&i.FieldID,
		&i.FieldName,
		&i.DomainID,
		&i.DomainName,
		&i.WorksCount,
		&i.UpdatedAt,
	)
	return i, err
}

const listDistinctFields = `-- name: ListDistinctFields :many
SELECT DISTINCT field_id, field_name, domain_id, domain_name
FROM openalex_topics
WHERE field_id != ''
ORDER BY domain_name, field_name
`

type ListDistinctFieldsRow struct {
	FieldID    string
	FieldName  string
	DomainID   string
	DomainName string
}

func (q *Queries) ListDistinctFields(ctx context.Context) ([]ListDistinctFieldsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctFields)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDistinctFieldsRow
	for rows.Next() {
		var i ListDistinctFieldsRow
		if err := rows.Scan(
			&i.FieldID,
			&i.FieldName,
			&i.DomainID,
			&i.DomainName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctSubfieldsByField = `-- name: ListDistinctSubfieldsByField :many
SELECT DISTINCT subfield_id, subfield_name
FROM openalex_topics
WHERE field_id = ?
ORDER BY subfield_name
`

type ListDistinctSubfieldsByFieldRow struct {
	SubfieldID   string
	SubfieldName string
}

func (q *Queries) ListDistinctSubfieldsByField(ctx context.Context, fieldID string) ([]ListDistinctSubfieldsByFieldRow, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctSubfieldsByField, fieldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDistinctSubfieldsByFieldRow
	for rows.Next() {
		var i ListDistinctSubfieldsByFieldRow
		if err := rows.Scan(&i.SubfieldID, &i.SubfieldName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopicsBySubfield = `-- name: ListTopicsBySubfield :many
SELECT openalex_id, display_name, description, keywords
FROM openalex_topics
WHERE subfield_id = ?
ORDER BY works_count DESC
`

type ListTopicsBySubfieldRow struct {
	OpenalexID  string
	DisplayName string
	Description string
	Keywords    string
}

func (q *Queries) ListTopicsBySubfield(ctx context.Context, subfieldID string) ([]ListTopicsBySubfieldRow, error) {
	rows, err := q.db.QueryContext(ctx, listTopicsBySubfield, subfieldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopicsBySubfieldRow
	for rows.Next() {
		var i ListTopicsBySubfieldRow
		if err := rows.Scan(
			&i.OpenalexID,
			&i.DisplayName,
			&i.Description,
			&i.Keywords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOpenAlexTopic = `-- name: UpsertOpenAlexTopic :exec
INSERT INTO openalex_topics (openalex_id, display_name, description, keywords, subfield_id, subfield_name, field_id, field_name, domain_id, domain_name, works_count, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(openalex_id) DO UPDATE SET
    display_name = excluded.display_name,
    description = excluded.description,
    keywords = excluded.keywords,
    subfield_id = excluded.subfield_id,
    subfield_name = excluded.subfield_name,
    field_id = excluded.field_id,
    field_name = excluded.field_name,
    domain_id = excluded.domain_id,
    domain_name = excluded.domain_name,
    works_count = excluded.works_count,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertOpenAlexTopicParams struct {
	OpenalexID   string
	DisplayName  string
	Description  string
	Keywords     string
	SubfieldID   string
	SubfieldName string
	FieldID      string
	FieldName    string
	DomainID     string
	DomainName   string
	WorksCount   int64
}

func (q *Queries) UpsertOpenAlexTopic(ctx context.Context, arg UpsertOpenAlexTopicParams) error {
	_, err := q.db.ExecContext(ctx, upsertOpenAlexTopic,
		arg.OpenalexID,
		arg.DisplayName,
		arg.Description,
		arg.Keywords,
		arg.SubfieldID,
		arg.SubfieldName,
		arg.FieldID,
		arg.FieldName,
		arg.DomainID,
		arg.DomainName,
		arg.WorksCount,
	)
	return err
}
