// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: publications.sql

package db

import (
	"context"
)

const countPublicationsByResearcher = `-- name: CountPublicationsByResearcher :one
SELECT COUNT(*) FROM publications WHERE researcher_id = ?
`

func (q *Queries) CountPublicationsByResearcher(ctx context.Context, researcherID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublicationsByResearcher, researcherID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listPublicationsByResearcher = `-- name: ListPublicationsByResearcher :many
SELECT id, openalex_id, researcher_id, title, publication_date, doi, cited_by_count, created_at FROM publications
WHERE researcher_id = ?
ORDER BY publication_date DESC
LIMIT ?
`

type ListPublicationsByResearcherParams struct {
	ResearcherID string
	Limit        int64
}

func (q *Queries) ListPublicationsByResearcher(ctx context.Context, arg ListPublicationsByResearcherParams) ([]Publication, error) {
	rows, err := q.db.QueryContext(ctx, listPublicationsByResearcher, arg.ResearcherID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Publication
	for rows.Next() {
		var i Publication
		if err := rows.Scan(
			&i.ID,
			&i.OpenalexID,
			&i.ResearcherID,
			&i.Title,
			&i.PublicationDate,
			&i.Doi,
			&i.CitedByCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPublication = `-- name: UpsertPublication :exec
INSERT INTO publications (openalex_id, researcher_id, title, publication_date, doi, cited_by_count)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(openalex_id) DO UPDATE SET
    title = excluded.title,
    cited_by_count = excluded.cited_by_count
`

type UpsertPublicationParams struct {
	OpenalexID      string
	ResearcherID    string
	Title           string
	PublicationDate string
	Doi             string
	CitedByCount    int64
}

func (q *Queries) UpsertPublication(ctx context.Context, arg UpsertPublicationParams) error {
	_, err := q.db.ExecContext(ctx, upsertPublication,
		arg.OpenalexID,
		arg.ResearcherID,
		arg.Title,
		arg.PublicationDate,
		arg.Doi,
		arg.CitedByCount,
	)
	return err
}
