// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: researchers.sql

package db

import (
	"context"
	"database/sql"
)

const createResearcher = `-- name: CreateResearcher :one
INSERT INTO researchers (id, openalex_id, name, affiliation, h_index, works_count, cited_by_count, relevancy_threshold)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, openalex_id, name, affiliation, h_index, works_count, cited_by_count, relevancy_threshold, last_synced_at, created_at, research_interests, email
`

type CreateResearcherParams struct {
	ID                 string
	OpenalexID         string
	Name               string
	Affiliation        string
	HIndex             int64
	WorksCount         int64
	CitedByCount       int64
	RelevancyThreshold float64
}

func (q *Queries) CreateResearcher(ctx context.Context, arg CreateResearcherParams) (Researcher, error) {
	row := q.db.QueryRowContext(ctx, createResearcher,
		arg.ID,
		arg.OpenalexID,
		arg.Name,
		arg.Affiliation,
		arg.HIndex,
		arg.WorksCount,
		arg.CitedByCount,
		arg.RelevancyThreshold,
	)
	var i Researcher
	err := row.Scan(
		&i.ID,
		&i.OpenalexID,
		&i.Name,
		&i.Affiliation,
		&i.HIndex,
		&i.WorksCount,
		&i.CitedByCount,
		&i.RelevancyThreshold,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.ResearchInterests,
		&i.Email,
	)
	return i, err
}

const deleteResearcher = `-- name: DeleteResearcher :exec
DELETE FROM researchers WHERE id = ?
`

func (q *Queries) DeleteResearcher(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteResearcher, id)
	return err
}

const getResearcher = `-- name: GetResearcher :one
SELECT id, openalex_id, name, affiliation, h_index, works_count, cited_by_count, relevancy_threshold, last_synced_at, created_at, research_interests, email FROM researchers WHERE id = ? LIMIT 1
`

func (q *Queries) GetResearcher(ctx context.Context, id string) (Researcher, error) {
	row := q.db.QueryRowContext(ctx, getResearcher, id)
	var i Researcher
	err := row.Scan(
		&i.ID,
		&i.OpenalexID,
		&i.Name,
		&i.Affiliation,
		&i.HIndex,
		&i.WorksCount,
		&i.CitedByCount,
		&i.RelevancyThreshold,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.ResearchInterests,
		&i.Email,
	)
	return i, err
}

const getResearcherByEmail = `-- name: GetResearcherByEmail :one
SELECT id, openalex_id, name, affiliation, h_index, works_count, cited_by_count, relevancy_threshold, last_synced_at, created_at, research_interests, email FROM researchers WHERE email = ? LIMIT 1
`

func (q *Queries) GetResearcherByEmail(ctx context.Context, email sql.NullString) (Researcher, error) {
	row := q.db.QueryRowContext(ctx, getResearcherByEmail, email)
	var i Researcher
	err := row.Scan(
		&i.ID,
		&i.OpenalexID,
		&i.Name,
		&i.Affiliation,
		&i.HIndex,
		&i.WorksCount,
		&i.CitedByCount,
		&i.RelevancyThreshold,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.ResearchInterests,
		&i.Email,
	)
	return i, err
}

const getResearcherByOpenAlexID = `-- name: GetResearcherByOpenAlexID :one
SELECT id, openalex_id, name, affiliation, h_index, works_count, cited_by_count, relevancy_threshold, last_synced_at, created_at, research_interests, email FROM researchers WHERE openalex_id = ? LIMIT 1
`

func (q *Queries) GetResearcherByOpenAlexID(ctx context.Context, openalexID string) (Researcher, error) {
	row := q.db.QueryRowContext(ctx, getResearcherByOpenAlexID, openalexID)
	var i Researcher
	err := row.Scan(
		&i.ID,
		&i.OpenalexID,
		&i.Name,
		&i.Affiliation,
		&i.HIndex,
		&i.WorksCount,
		&i.CitedByCount,
		&i.RelevancyThreshold,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.ResearchInterests,
		&i.Email,
	)
	return i, err
}

const linkResearcherEmail = `-- name: LinkResearcherEmail :exec
UPDATE researchers SET email = ? WHERE id = ?
`

type LinkResearcherEmailParams struct {
	Email sql.NullString
	ID    string
}

func (q *Queries) LinkResearcherEmail(ctx context.Context, arg LinkResearcherEmailParams) error {
	_, err := q.db.ExecContext(ctx, linkResearcherEmail, arg.Email, arg.ID)
	return err
}

const listResearchers = `-- name: ListResearchers :many
SELECT id, openalex_id, name, affiliation, h_index, works_count, cited_by_count, relevancy_threshold, last_synced_at, created_at, research_interests, email FROM researchers ORDER BY name
`

func (q *Queries) ListResearchers(ctx context.Context) ([]Researcher, error) {
	rows, err := q.db.QueryContext(ctx, listResearchers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Researcher
	for rows.Next() {
		var i Researcher
		if err := rows.Scan(
			&i.ID,
			&i.OpenalexID,
			&i.Name,
			&i.Affiliation,
			&i.HIndex,
			&i.WorksCount,
			&i.CitedByCount,
			&i.RelevancyThreshold,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.ResearchInterests,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResearcherInterests = `-- name: UpdateResearcherInterests :exec
UPDATE researchers SET research_interests = ? WHERE id = ?
`

type UpdateResearcherInterestsParams struct {
	ResearchInterests string
	ID                string
}

func (q *Queries) UpdateResearcherInterests(ctx context.Context, arg UpdateResearcherInterestsParams) error {
	_, err := q.db.ExecContext(ctx, updateResearcherInterests, arg.ResearchInterests, arg.ID)
	return err
}

const updateResearcherStats = `-- name: UpdateResearcherStats :exec
UPDATE researchers
SET name = ?, affiliation = ?, h_index = ?, works_count = ?, cited_by_count = ?, last_synced_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateResearcherStatsParams struct {
	Name         string
	Affiliation  string
	HIndex       int64
	WorksCount   int64
	CitedByCount int64
	ID           string
}

func (q *Queries) UpdateResearcherStats(ctx context.Context, arg UpdateResearcherStatsParams) error {
	_, err := q.db.ExecContext(ctx, updateResearcherStats,
		arg.Name,
		arg.Affiliation,
		arg.HIndex,
		arg.WorksCount,
		arg.CitedByCount,
		arg.ID,
	)
	return err
}

const updateResearcherThreshold = `-- name: UpdateResearcherThreshold :exec
UPDATE researchers SET relevancy_threshold = ? WHERE id = ?
`

type UpdateResearcherThresholdParams struct {
	RelevancyThreshold float64
	ID                 string
}

func (q *Queries) UpdateResearcherThreshold(ctx context.Context, arg UpdateResearcherThresholdParams) error {
	_, err := q.db.ExecContext(ctx, updateResearcherThreshold, arg.RelevancyThreshold, arg.ID)
	return err
}
