// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scanned_works.sql

package db

import (
	"context"
	"database/sql"
)

const deleteScannedWorksByMonth = `-- name: DeleteScannedWorksByMonth :exec
DELETE FROM scanned_works WHERE researcher_id = ? AND scan_month = ?
`

type DeleteScannedWorksByMonthParams struct {
	ResearcherID string
	ScanMonth    string
}

func (q *Queries) DeleteScannedWorksByMonth(ctx context.Context, arg DeleteScannedWorksByMonthParams) error {
	_, err := q.db.ExecContext(ctx, deleteScannedWorksByMonth, arg.ResearcherID, arg.ScanMonth)
	return err
}

const deleteScannedWorksByResearcher = `-- name: DeleteScannedWorksByResearcher :exec
DELETE FROM scanned_works WHERE researcher_id = ?
`

func (q *Queries) DeleteScannedWorksByResearcher(ctx context.Context, researcherID string) error {
	_, err := q.db.ExecContext(ctx, deleteScannedWorksByResearcher, researcherID)
	return err
}

const listScannedWorksByMonth = `-- name: ListScannedWorksByMonth :many
SELECT id, researcher_id, scan_month, openalex_id, title, doi, publication_date, cited_by_count, abstract, authorships, topics, fetched_at, source_name, source_citedness FROM scanned_works
WHERE researcher_id = ? AND scan_month = ?
ORDER BY cited_by_count DESC
`

type ListScannedWorksByMonthParams struct {
	ResearcherID string
	ScanMonth    string
}

func (q *Queries) ListScannedWorksByMonth(ctx context.Context, arg ListScannedWorksByMonthParams) ([]ScannedWork, error) {
	rows, err := q.db.QueryContext(ctx, listScannedWorksByMonth, arg.ResearcherID, arg.ScanMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScannedWork
	for rows.Next() {
		var i ScannedWork
		if err := rows.Scan(
			&i.ID,
			&i.ResearcherID,
			&i.ScanMonth,
			&i.OpenalexID,
			&i.Title,
			&i.Doi,
			&i.PublicationDate,
			&i.CitedByCount,
			&i.Abstract,
			&i.Authorships,
			&i.Topics,
			&i.FetchedAt,
			&i.SourceName,
			&i.SourceCitedness,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertScannedWork = `-- name: UpsertScannedWork :exec
INSERT INTO scanned_works (researcher_id, scan_month, openalex_id, title, doi, publication_date, cited_by_count, abstract, authorships, topics, source_name, source_citedness)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(researcher_id, openalex_id, scan_month) DO UPDATE SET
    title = excluded.title,
    doi = excluded.doi,
    publication_date = excluded.publication_date,
    cited_by_count = excluded.cited_by_count,
    abstract = excluded.abstract,
    authorships = excluded.authorships,
    topics = excluded.topics,
    source_name = excluded.source_name,
    source_citedness = excluded.source_citedness,
    fetched_at = CURRENT_TIMESTAMP
`

type UpsertScannedWorkParams struct {
	ResearcherID    string
	ScanMonth       string
	OpenalexID      string
	Title           string
	Doi             sql.NullString
	PublicationDate sql.NullString
	CitedByCount    sql.NullInt64
	Abstract        sql.NullString
	Authorships     string
	Topics          string
	SourceName      string
	SourceCitedness float64
}

func (q *Queries) UpsertScannedWork(ctx context.Context, arg UpsertScannedWorkParams) error {
	_, err := q.db.ExecContext(ctx, upsertScannedWork,
		arg.ResearcherID,
		arg.ScanMonth,
		arg.OpenalexID,
		arg.Title,
		arg.Doi,
		arg.PublicationDate,
		arg.CitedByCount,
		arg.Abstract,
		arg.Authorships,
		arg.Topics,
		arg.SourceName,
		arg.SourceCitedness,
	)
	return err
}
