// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scanned_works.sql

package db

import (
	"context"
	"database/sql"
)

const deleteScannedWorksByResearcher = `-- name: DeleteScannedWorksByResearcher :exec
DELETE FROM scanned_works WHERE researcher_id = ?
`

func (q *Queries) DeleteScannedWorksByResearcher(ctx context.Context, researcherID int64) error {
	_, err := q.db.ExecContext(ctx, deleteScannedWorksByResearcher, researcherID)
	return err
}

const deleteScannedWorksByWeek = `-- name: DeleteScannedWorksByWeek :exec
DELETE FROM scanned_works WHERE researcher_id = ? AND scan_week = ?
`

type DeleteScannedWorksByWeekParams struct {
	ResearcherID int64
	ScanWeek     string
}

func (q *Queries) DeleteScannedWorksByWeek(ctx context.Context, arg DeleteScannedWorksByWeekParams) error {
	_, err := q.db.ExecContext(ctx, deleteScannedWorksByWeek, arg.ResearcherID, arg.ScanWeek)
	return err
}

const listScannedWorksByWeek = `-- name: ListScannedWorksByWeek :many
SELECT id, researcher_id, scan_week, openalex_id, title, doi, publication_date, cited_by_count, abstract, authorships, topics, fetched_at, source_name, source_citedness FROM scanned_works
WHERE researcher_id = ? AND scan_week = ?
ORDER BY cited_by_count DESC
`

type ListScannedWorksByWeekParams struct {
	ResearcherID int64
	ScanWeek     string
}

func (q *Queries) ListScannedWorksByWeek(ctx context.Context, arg ListScannedWorksByWeekParams) ([]ScannedWork, error) {
	rows, err := q.db.QueryContext(ctx, listScannedWorksByWeek, arg.ResearcherID, arg.ScanWeek)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScannedWork
	for rows.Next() {
		var i ScannedWork
		if err := rows.Scan(
			&i.ID,
			&i.ResearcherID,
			&i.ScanWeek,
			&i.OpenalexID,
			&i.Title,
			&i.Doi,
			&i.PublicationDate,
			&i.CitedByCount,
			&i.Abstract,
			&i.Authorships,
			&i.Topics,
			&i.FetchedAt,
			&i.SourceName,
			&i.SourceCitedness,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertScannedWork = `-- name: UpsertScannedWork :exec
INSERT INTO scanned_works (researcher_id, scan_week, openalex_id, title, doi, publication_date, cited_by_count, abstract, authorships, topics, source_name, source_citedness)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(researcher_id, openalex_id, scan_week) DO UPDATE SET
    title = excluded.title,
    doi = excluded.doi,
    publication_date = excluded.publication_date,
    cited_by_count = excluded.cited_by_count,
    abstract = excluded.abstract,
    authorships = excluded.authorships,
    topics = excluded.topics,
    source_name = excluded.source_name,
    source_citedness = excluded.source_citedness,
    fetched_at = CURRENT_TIMESTAMP
`

type UpsertScannedWorkParams struct {
	ResearcherID    int64
	ScanWeek        string
	OpenalexID      string
	Title           string
	Doi             sql.NullString
	PublicationDate sql.NullString
	CitedByCount    sql.NullInt64
	Abstract        sql.NullString
	Authorships     string
	Topics          string
	SourceName      string
	SourceCitedness float64
}

func (q *Queries) UpsertScannedWork(ctx context.Context, arg UpsertScannedWorkParams) error {
	_, err := q.db.ExecContext(ctx, upsertScannedWork,
		arg.ResearcherID,
		arg.ScanWeek,
		arg.OpenalexID,
		arg.Title,
		arg.Doi,
		arg.PublicationDate,
		arg.CitedByCount,
		arg.Abstract,
		arg.Authorships,
		arg.Topics,
		arg.SourceName,
		arg.SourceCitedness,
	)
	return err
}
