// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: topics.sql

package db

import (
	"context"
)

const deleteLLMTopicsByResearcher = `-- name: DeleteLLMTopicsByResearcher :exec
DELETE FROM topics WHERE researcher_id = ? AND source = 'llm'
`

func (q *Queries) DeleteLLMTopicsByResearcher(ctx context.Context, researcherID int64) error {
	_, err := q.db.ExecContext(ctx, deleteLLMTopicsByResearcher, researcherID)
	return err
}

const deleteOpenAlexTopicsByResearcher = `-- name: DeleteOpenAlexTopicsByResearcher :exec
DELETE FROM topics WHERE researcher_id = ? AND source = 'openalex'
`

func (q *Queries) DeleteOpenAlexTopicsByResearcher(ctx context.Context, researcherID int64) error {
	_, err := q.db.ExecContext(ctx, deleteOpenAlexTopicsByResearcher, researcherID)
	return err
}

const deleteTopic = `-- name: DeleteTopic :exec
DELETE FROM topics WHERE id = ? AND researcher_id = ?
`

type DeleteTopicParams struct {
	ID           int64
	ResearcherID int64
}

func (q *Queries) DeleteTopic(ctx context.Context, arg DeleteTopicParams) error {
	_, err := q.db.ExecContext(ctx, deleteTopic, arg.ID, arg.ResearcherID)
	return err
}

const deleteTopicsByResearcher = `-- name: DeleteTopicsByResearcher :exec
DELETE FROM topics WHERE researcher_id = ?
`

func (q *Queries) DeleteTopicsByResearcher(ctx context.Context, researcherID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTopicsByResearcher, researcherID)
	return err
}

const getTopic = `-- name: GetTopic :one
SELECT id, researcher_id, openalex_id, name, subfield, field, domain, score, created_at, source FROM topics WHERE id = ?
`

func (q *Queries) GetTopic(ctx context.Context, id int64) (Topic, error) {
	row := q.db.QueryRowContext(ctx, getTopic, id)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.ResearcherID,
		&i.OpenalexID,
		&i.Name,
		&i.Subfield,
		&i.Field,
		&i.Domain,
		&i.Score,
		&i.CreatedAt,
		&i.Source,
	)
	return i, err
}

const listTopTopicsByResearcher = `-- name: ListTopTopicsByResearcher :many
SELECT id, researcher_id, openalex_id, name, subfield, field, domain, score, created_at, source FROM topics
WHERE researcher_id = ?
ORDER BY score DESC
LIMIT ?
`

type ListTopTopicsByResearcherParams struct {
	ResearcherID int64
	Limit        int64
}

func (q *Queries) ListTopTopicsByResearcher(ctx context.Context, arg ListTopTopicsByResearcherParams) ([]Topic, error) {
	rows, err := q.db.QueryContext(ctx, listTopTopicsByResearcher, arg.ResearcherID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.ResearcherID,
			&i.OpenalexID,
			&i.Name,
			&i.Subfield,
			&i.Field,
			&i.Domain,
			&i.Score,
			&i.CreatedAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopicsByResearcher = `-- name: ListTopicsByResearcher :many
SELECT id, researcher_id, openalex_id, name, subfield, field, domain, score, created_at, source FROM topics
WHERE researcher_id = ?
ORDER BY score DESC
`

func (q *Queries) ListTopicsByResearcher(ctx context.Context, researcherID int64) ([]Topic, error) {
	rows, err := q.db.QueryContext(ctx, listTopicsByResearcher, researcherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.ResearcherID,
			&i.OpenalexID,
			&i.Name,
			&i.Subfield,
			&i.Field,
			&i.Domain,
			&i.Score,
			&i.CreatedAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTopicScore = `-- name: UpdateTopicScore :exec
UPDATE topics SET score = ?, source = 'manual' WHERE id = ? AND researcher_id = ?
`

type UpdateTopicScoreParams struct {
	Score        float64
	ID           int64
	ResearcherID int64
}

func (q *Queries) UpdateTopicScore(ctx context.Context, arg UpdateTopicScoreParams) error {
	_, err := q.db.ExecContext(ctx, updateTopicScore, arg.Score, arg.ID, arg.ResearcherID)
	return err
}

const upsertTopic = `-- name: UpsertTopic :exec
INSERT INTO topics (researcher_id, openalex_id, name, subfield, field, domain, score, source)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(researcher_id, openalex_id) DO UPDATE SET
    name = excluded.name,
    subfield = excluded.subfield,
    field = excluded.field,
    domain = excluded.domain,
    score = excluded.score,
    source = excluded.source
`

type UpsertTopicParams struct {
	ResearcherID int64
	OpenalexID   string
	Name         string
	Subfield     string
	Field        string
	Domain       string
	Score        float64
	Source       string
}

func (q *Queries) UpsertTopic(ctx context.Context, arg UpsertTopicParams) error {
	_, err := q.db.ExecContext(ctx, upsertTopic,
		arg.ResearcherID,
		arg.OpenalexID,
		arg.Name,
		arg.Subfield,
		arg.Field,
		arg.Domain,
		arg.Score,
		arg.Source,
	)
	return err
}
